"""empty message

Revision ID: e588a8ab659a
Revises: 
Create Date: 2023-06-26 00:54:50.399865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e588a8ab659a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentNumber', sa.String(length=100), nullable=True),
    sa.Column('loginDate', sa.Date(), nullable=False),
    sa.Column('loginTime', sa.Time(), nullable=False),
    sa.Column('logoutTime', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    # ### end Alembic commands ###
